version: '3'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tradexpro_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www
    networks:
      - tradexpro
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: tradexpro_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - tradexpro
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: tradexpro_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log-bin-trust-function-creators=1
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tradexpro

  # Redis Service
  redis:
    image: redis:alpine
    container_name: tradexpro_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - tradexpro

networks:
  tradexpro:
    driver: bridge

volumes:
  dbdata:
